version: '3'
services:
  web:
    image: vitaliifrontend:latest
    ports:
      - "80:80"
  json-server:
    image: vimagick/json-server
    command: -H 0.0.0.0 -p 3001 -w hotel.json
    ports:
      - "3001:3001"
    volumes:
      - ./data:/data
    restart: always
    