export const ROOMS_LOADING = 'ROOMS_LOADING';
export const ROOMS_FAILED = 'ROOMS_FAILED';
export const ADD_ROOMS = 'ADD_ROOMS';

export const POST_RESERVATION = 'POST_RESERVATION';
export const ADD_ALL_RESERVATION = 'ADD_ALL_RESERVATION';
export const ALL_RESERVATION_FAILED = 'ALL_RESERVATION_FAILED';

export const POST_CONTACT_FORM = 'POST_CONTACT_FORM';
export const ADD_CONTACT_FORM = 'ADD_CONTACT_FORM';
export const CONTACT_FORM_FAILED = 'CONTACT_FORM_FAILED';

export const SERVICES_LOADING ='SERVICES_LOADING';
export const ADD_SERVICES = 'ADD_SERVICES';
export const SERVICES_FAILED = 'SERVICES_FAILED';